// Generated by tools/generate-sport-skills.ts — do not edit.
import skill0 from "../skills/zone-reference.md";

export const skills: ReadonlyArray<{ readonly name: string; readonly content: string }> = [
  { name: "zone-reference", content: skill0 },
];
