#!/usr/bin/env tsx
/**
 * Codegen: scans <pkgDir>/skills/*.md and writes <pkgDir>/src/skills.generated.ts
 * with raw-text imports for each .md file. The generated file is gitignored
 * (re-emitted on every build); tsup's `.md: text` loader inlines the content
 * into the bundle so installed packages don't need filesystem access at runtime.
 *
 * Usage: tsx tools/generate-sport-skills.ts <pkgDir>
 */
import { readdirSync, writeFileSync, renameSync, mkdtempSync } from "node:fs";
import { join, basename } from "node:path";
import { tmpdir } from "node:os";

const pkgDir = process.argv[2];
if (!pkgDir) {
  console.error("usage: generate-sport-skills.ts <packageDirectory>");
  process.exit(1);
}

const skillsDir = join(pkgDir, "skills");
const targetFile = join(pkgDir, "src", "skills.generated.ts");

const skills = readdirSync(skillsDir)
  .filter((f) => f.endsWith(".md"))
  .map((f) => basename(f, ".md"))
  .sort();

const imports = skills
  .map((s, i) => `import skill${i} from "../skills/${s}.md";`)
  .join("\n");

const arr = skills
  .map((s, i) => `  { name: ${JSON.stringify(s)}, content: skill${i} },`)
  .join("\n");

const content = `// Generated by tools/generate-sport-skills.ts — do not edit.
${imports}

export const skills: ReadonlyArray<{ readonly name: string; readonly content: string }> = [
${arr}
];
`;

// Atomic write (PG-14): tmp file + rename so a partial write never leaves
// a half-baked skills.generated.ts on disk.
const tmpDir = mkdtempSync(join(tmpdir(), "sport-skills-"));
const tmpFile = join(tmpDir, "skills.generated.ts");
writeFileSync(tmpFile, content, "utf-8");
renameSync(tmpFile, targetFile);

console.log(`Wrote ${skills.length} skills to ${targetFile}`);
