import { mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { afterEach, describe, expect, it } from "vitest";

const script = fileURLToPath(new URL("./generate-sport-skills.ts", import.meta.url));
const fixtures: string[] = [];

afterEach(() => {
  for (const fixture of fixtures.splice(0)) {
    rmSync(fixture, { recursive: true, force: true });
  }
});

describe("generate-sport-skills", () => {
  it("stages beside the target without using the operating-system temp directory", () => {
    const fixture = mkdtempSync(join(tmpdir(), "sport-skills-test-"));
    fixtures.push(fixture);
    const pkgDir = join(fixture, "sport-example");
    const skillsDir = join(pkgDir, "skills");
    const srcDir = join(pkgDir, "src");
    const unusableTemp = join(fixture, "not-a-directory");
    mkdirSync(skillsDir, { recursive: true });
    mkdirSync(srcDir, { recursive: true });
    writeFileSync(join(skillsDir, "zeta.md"), "Zeta skill\n", "utf8");
    writeFileSync(join(skillsDir, "alpha.md"), "Alpha skill\n", "utf8");
    writeFileSync(unusableTemp, "blocked\n", "utf8");

    const result = spawnSync(process.execPath, ["--import", "tsx", script, pkgDir], {
      cwd: process.cwd(),
      encoding: "utf8",
      env: {
        ...process.env,
        TMPDIR: unusableTemp,
        TEMP: unusableTemp,
        TMP: unusableTemp,
        TSX_DISABLE_CACHE: "1",
      },
    });

    expect(result.status, result.stderr).toBe(0);
    expect(readFileSync(join(srcDir, "skills.generated.ts"), "utf8")).toBe(`// Generated by tools/generate-sport-skills.ts — do not edit.
import skill0 from "../skills/alpha.md";
import skill1 from "../skills/zeta.md";

export const skills: ReadonlyArray<{ readonly name: string; readonly content: string }> = [
  { name: "alpha", content: skill0 },
  { name: "zeta", content: skill1 },
];
`);
    expect(readdirSync(srcDir)).toEqual(["skills.generated.ts"]);
  });
});
